variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "availability_zones" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "gwlb_ips" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "num_of_fgts_per_az" {}
variable "instance_type" {}
variable "cidr_for_access" {}
variable "keypair" {}
variable "encrypt_volumes" {}
variable "fortios_version" {}
variable "license_type" {}
variable "license_files_for_1st_fgt_per_az" {}
variable "license_files_for_2nd_fgt_per_az" {}
variable "flex_tokens_for_1st_fgt_per_az" {}
variable "flex_Tokens_for_2nd_fgt_per_az" {}
variable "tag_name_prefix" {}