variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "vpc_cidr" {}
variable "availability_zones" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "gwlb_subnet_cidrs" {}
variable "attachment_creation" {}
variable "tgw_creation" {}
variable "cwan_creation" {}
variable "attachment_subnet_cidrs" {}
variable "transit_gateway_id" {}
variable "tgw_security_route_table_id" {}
variable "tgw_spoke_route_table_id" {}
variable "cwan_id" {}
variable "cwan_arn" {}
variable "cwan_segment" {}
variable "cwan_policy_state" {}
variable "gwlb_endpoint_service_name" {}
variable "gwlb_endpoint_service_type" {}
variable "tag_name_prefix" {}
variable "tag_name_unique" {}