variable "region" {}
variable "availability_zones" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "gwlb_ips" {}
variable "gwlb_target_group_arn" {}
variable "public_subnet_ids" {}
variable "private_subnet_ids" {}
variable "num_of_fgts_per_az" {}
variable "arm_mode" {}
variable "internet_access" {}
variable "dedicated_management" {}
variable "dedicated_management_placement" {}
variable "instance_type" {}
variable "cidr_for_access" {}
variable "keypair" {}
variable "encrypt_volumes" {}
variable "fortios_version" {}
variable "license_type" {}
variable "license_files" {}
variable "flex_tokens" {}
variable "tag_name_prefix" {}